                                        ; -*- mode: Lisp -*-
(nil . ((cmake-ide-project-dir . "./")
         (cmake-ide-build-dir . "build/")
         (cmake-ide-cmake-opts . "-GNinja -DCMAKE_BUILD_TYPE=Debug -DBUILD_COVERAGE=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DBUILD_DEPENDENCIES=OFF")
        (helm-make-build-dir . "build/")
        (helm-make-arguments . "-j4")
        (indent-tabs-mode . nil)
        (tab-width . 4)
        (c-basic-offset . 'tab-width)
        (projectile-project-name . "tsm")
        (projectile-project-run-cmd . "ctest")
        (projectile-project-test-cmd . "ctest")
        (helm-ctest-build-dir . "build/")
        (helm-make-build-dir . "build/")
        (helm-make-arguments . "-j4")))
