name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake g++

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build -- -j2

    - name: Test (optional)
      run: |
        cd build
        ./bin/tsm_test

