name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake ninja-build graphviz doxygen lcov g++ valgrind

    - name: Configure CMake
      run: cmake -S . -B build -G Ninja -DBUILD_DOCUMENTATION=ON -DBUILD_COVERAGE=ON

    - name: Build
      run: cmake --build build -- -j2

    - name: Test (optional)
      run: |
        cd build
        ctest

